NVMem: fix build issue when FILE_BACKED_NV is set to 0
TrustedComputingGroup/TPM pull request #7
Opened 2024-11-12 10:02 UTC by stefano-garzarella

If FILE_BACKED_NV is set to NO(0), the `delete` variable is unused, causing a compiler warning:

    Platform/src/NVMem.c: In function ‘_plat__NVDisable’:
    Platform/src/NVMem.c:185:9: error: unused variable ‘delete’ [-Werror=unused-variable]
      185 |     int delete = ((intptr_t)platParameter != 0)
          |         ^~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:2674: Platform/src/libplatform_a-NVMem.o] Error 1

Move its declaration into the nested block where it is used.

2024-11-12 18:34 UTC, bradlitterell requested changes

2024-11-12 18:34 UTC, bradlitterell commented on TPMCmd/Platform/src/NVMem.c
> +        int delete = ((intptr_t)platParameter != 0)
I would rather leave the interpretation of the parameter (the check and cast to boolean) outside the `#if` because I don't want the **meaning** of the parameter to depend upon the `#ifdef`.  Instead just add a reference to the variable in a `#else` (or immediately after calculating it), to silence the warning.

2024-11-13 08:18 UTC, stefano-garzarella commented on TPMCmd/Platform/src/NVMem.c
> +        int delete = ((intptr_t)platParameter != 0)
I see.

I'll add `NOT_REFERENCED(delete)` immediately after calculating it.

2024-11-13 08:27 UTC, stefano-garzarella commented
v2:
- used NOT_REFERENCED() instead of moving the declaration in the #if [@bradlitterell]

2024-11-15 23:56 UTC, bradlitterell approved these changes
Looks good, thank you!

2024-11-15 23:57 UTC, merged